[build]
builder = "nixpacks"

[deploy]
startCommand = "php -c /app/php.ini -S 0.0.0.0:$PORT index.php"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
